name: Deploy Ghost Theme

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Verify build environment
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Gulp version: $(npx gulp --version)"
        
      - name: Build theme assets
        run: npx gulp build
        
      - name: Create theme package
        run: npm run zip
        
      - name: Verify theme package
        run: |
          ls -la dist/
          if [ -f "dist/solo-erin.zip" ]; then
            echo "Theme package created successfully"
            ls -lh dist/solo-erin.zip
          else
            echo "ERROR: Theme package not found"
            exit 1
          fi
        
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
